self.ar_ops = {
    _ast.Add: "+",
    _ast.Sub: "-",
    _ast.Mult: "*",
    _ast.MatMult: "@",
    _ast.Div: "/",
    _ast.Mod: "%",
    _ast.Pow: "**",
    _ast.LShift: "<<",
    _ast.RShift: ">>",
    _ast.BitOr: "|",
    _ast.BitXor: "^",
    _ast.BitAnd: "&",
    _ast.FloorDiv: "//",
}
